import { useEffect, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { workflowRequest, type WorkflowRecord } from "../lib/workflowApi";
import { capturePendingVerification, clearPendingVerification } from "../lib/pendingVerification";
interface Status { emailVerified: boolean; emailEnabled: boolean; mailLimit: number }
const input = "mt-1 block w-full rounded-lg border border-gray-300 p-2.5";
const button = "min-h-11 rounded-lg border border-brand-200 px-4 py-2 text-sm text-brand-800 disabled:opacity-50";
const sessionDate = (value: unknown) => {
  if (value === null || value === undefined || value === "") return "—";
  const numeric = typeof value === "number" || /^\d+$/.test(String(value)) ? Number(value) : null;
  const date = numeric === null ? new Date(String(value)) : new Date(numeric < 1e12 ? numeric * 1000 : numeric);
  return Number.isNaN(date.getTime()) ? "日時不明" : date.toLocaleString("ja-JP", { timeZone: "Asia/Tokyo" });
};
export default function AccountSecurity() {
  const { logout } = useAuth();
  const [status, setStatus] = useState<Status | null>(null); const [sessions, setSessions] = useState<WorkflowRecord[]>([]); const [notifications, setNotifications] = useState<WorkflowRecord[]>([]);
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [revision, setRevision] = useState(0);
  const [token, setToken] = useState(capturePendingVerification);
  useEffect(() => { let active = true; setError(""); Promise.all([workflowRequest<Status>("/account-security/status"), workflowRequest<WorkflowRecord[]>("/account-security/sessions"), workflowRequest<WorkflowRecord[]>("/account-security/notifications")]).then(([s, list, notices]) => { if (active) { setStatus(s); setSessions(list); setNotifications(notices); } }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [revision]);
  async function act(action: () => Promise<unknown>, success: string) { setBusy(true); setError(""); setMessage(""); try { const result = await action() as { sent?: boolean; reason?: string } | undefined; setMessage(result?.sent === false ? result.reason || "メールは送信されませんでした" : success); setRevision(n => n + 1); } catch (e) { setError(e instanceof Error ? e.message : "処理に失敗しました"); } finally { setBusy(false); } }
  const post = (path: string, body: unknown) => workflowRequest(`/account-security/${path}`, { method: "POST", body: JSON.stringify(body) });
  function confirm(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); void act(async () => { await post("verify-email/confirm", { token: f.get("token") }); clearPendingVerification(); setToken(""); }, "メールアドレスを確認しました"); }
  const verificationLink = token && <section className="rounded-xl border bg-white p-5"><p className="text-sm">メールの確認リンクを受け取りました。</p><button disabled={busy} className={`${button} mt-3`} onClick={() => void act(async () => { await post("verify-email/confirm", { token }); clearPendingVerification(); setToken(""); }, "メールアドレスを確認しました")}>このメールアドレスを確認する</button></section>;
  return <main className="min-h-screen bg-gray-50 p-4 sm:p-8"><div className="mx-auto max-w-3xl space-y-5"><Link to="/app" className="text-sm text-brand-700">← ワークスペースへ</Link><h1 className="text-2xl font-bold">アカウントの安全管理</h1>{verificationLink}{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error} <button onClick={() => setRevision(n => n + 1)} className="underline">再読み込み</button></p>}{message && <p role="status" className="rounded-lg bg-brand-50 p-3 text-sm">{message}</p>}
    <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">メールアドレスの本人確認</h2>{!status ? <p className="mt-3 text-sm">読み込み中…</p> : <><p className="mt-3 text-sm">{status.emailVerified ? "確認済み" : "未確認"}</p>{!status.emailEnabled && <p className="mt-2 text-sm text-amber-800">メール送信は未設定のため確認メールを送信できません。</p>}{!status.emailVerified && <><button className={`${button} mt-3`} disabled={busy || !status.emailEnabled} onClick={() => void act(() => post("verify-email/request", {}), "確認メールを送信しました。受信したメールをご確認ください。")}>確認メールを送る</button><form className="mt-4 space-y-3" onSubmit={confirm}><label className="block text-sm">メールに記載された確認トークン<input name="token" required autoComplete="off" className={input} /></label><button className={button} disabled={busy}>本人確認を完了</button></form></>}</>}</section>
    <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">ログイン中の端末</h2><div className="mt-3 space-y-3">{sessions.map(session => <div key={session.id} className="rounded-lg border p-3 text-sm"><p className="break-all">{String(session.userAgent || "端末情報なし")}</p><p className="mt-1 text-gray-500">最終利用: {sessionDate(session.lastSeenAt)} / 有効期限: {sessionDate(session.expiresAt)}</p>{session.current ? <span className="mt-2 inline-block text-brand-700">この端末</span> : <button className={`${button} mt-2`} disabled={busy} onClick={() => void act(() => workflowRequest(`/account-security/sessions/${encodeURIComponent(session.id)}`, { method: "DELETE" }), "端末のセッションを終了しました")}>この端末を終了</button>}</div>)}</div><form className="mt-5 space-y-3 border-t pt-4" onSubmit={event => { event.preventDefault(); const f = new FormData(event.currentTarget); void act(async () => { await post("logout-all", { password: f.get("password"), ...(f.get("code") ? { code: f.get("code") } : {}) }); await logout(); }, "全端末のログインを終了しました"); }}><h3 className="text-sm font-medium">全端末からログアウト</h3><label className="block text-sm">現在のパスワード<input name="password" type="password" required autoComplete="current-password" className={input} /></label><label className="block text-sm">二段階認証コード（有効な場合）<input name="code" inputMode="numeric" autoComplete="one-time-code" className={input} /></label><button className={button} disabled={busy}>全端末のログインを終了</button></form></section>
    <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">通知</h2>{notifications.length === 0 && <p className="mt-3 text-sm text-gray-500">通知はありません。</p>}<div className="mt-3 space-y-3">{notifications.map(notice => <article key={notice.id} className="rounded-lg border p-3"><h3 className="break-words text-sm font-medium">{String(notice.title || "お知らせ")}</h3><p className="mt-1 break-words text-sm text-gray-600">{String(notice.message || notice.body || "")}</p>{!notice.readAt && <button className={`${button} mt-2`} disabled={busy} onClick={() => void act(() => post(`notifications/${encodeURIComponent(notice.id)}/read`, {}), "既読にしました")}>既読にする</button>}</article>)}</div></section>
  </div></main>;
}
