import { useEffect, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { useBusiness } from "../context/BusinessContext";
import { useAuth } from "../context/AuthContext";
import { downloadWorkflow, workflowPath, workflowRequest, type WorkflowOverview, type WorkflowRecord } from "../lib/workflowApi";
const tabs = [["overview", "確認待ち"], ["reviews", "レビュー"], ["evidence", "証憑"], ["history", "変更履歴"], ["lock", "締め・提出"], ["recurring", "定期処理"], ["guide", "入力ガイド"]];
const input = "mt-1 block w-full min-w-0 rounded-lg border border-gray-300 p-2.5";
const button = "min-h-11 rounded-lg border border-brand-200 bg-brand-50 px-4 py-2 text-sm text-brand-800 disabled:opacity-50";
const text = (value: unknown) => typeof value === "string" || typeof value === "number" ? String(value) : "";
interface Entities { entries: { id: string; entryNumber: number; description: string; entryDate: string }[]; invoices: { id: string; invoiceNumber: string; issueDate: string; partnerName: string }[] }
const fieldLabels: Record<string, string> = { id: "管理番号", entityType: "対象種類", entityId: "対象", message: "コメント", status: "状態", userId: "投稿者", createdAt: "作成日時", updatedAt: "更新日時", fileName: "原本名", mimeType: "形式", size: "サイズ", digest: "原本ハッシュ", entryId: "関連仕訳", invoiceId: "関連請求書", name: "名前", kind: "種類", sourceId: "元データ", dayOfMonth: "毎月の日", description: "摘要", entryDate: "取引日", entryNumber: "仕訳番号", action: "操作", actorId: "操作ユーザー", invoiceNumber: "請求書番号", partnerName: "取引先", score: "一致度", count: "件数", entryIds: "対象仕訳", sourceEntryId: "候補元仕訳" };
const statusLabels: Record<string, string> = { JOURNAL: "仕訳", INVOICE: "請求書", COMMENT: "コメント", CHANGES_REQUESTED: "修正依頼", APPROVED: "確認済み", RESOLVED: "対応済み", DRAFT: "下書き" };
const displayValue = (value: unknown): string => Array.isArray(value) ? value.map(displayValue).join("、") : value && typeof value === "object" ? Object.values(value).map(displayValue).filter(Boolean).join(" / ") : statusLabels[text(value)] || text(value) || "—";
export default function Operations() {
  const { currentBusiness } = useBusiness();
  return currentBusiness ? <OperationsWorkspace key={currentBusiness.id} businessId={currentBusiness.id} viewer={currentBusiness.accessRole === "VIEWER"} owner={!!currentBusiness.isOwner} /> : null;
}
function OperationsWorkspace({ businessId, viewer, owner }: { businessId: string; viewer: boolean; owner: boolean }) {
  const { user } = useAuth();
  const [tab, setTab] = useState("overview"); const [overview, setOverview] = useState<WorkflowOverview | null>(null);
  const [rows, setRows] = useState<WorkflowRecord[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [revision, setRevision] = useState(0);
  const [entities, setEntities] = useState<Entities>({ entries: [], invoices: [] });
  const [reviewType, setReviewType] = useState("JOURNAL"); const [reviewId, setReviewId] = useState("");
  const [recurringKind, setRecurringKind] = useState("JOURNAL"); const [sourceId, setSourceId] = useState("");
  const [guideMode, setGuideMode] = useState<"suggestions" | "duplicates">("suggestions");
  const options = (kind: string) => kind === "JOURNAL" ? entities.entries.map(row => <option key={row.id} value={row.id}>{row.entryDate} · #{row.entryNumber} {row.description}</option>) : entities.invoices.map(row => <option key={row.id} value={row.id}>{row.issueDate} · {row.invoiceNumber} {row.partnerName}</option>);
  useEffect(() => { let active = true; setEntities({ entries: [], invoices: [] }); workflowRequest<Entities>(workflowPath(businessId, "entities")).then(data => { if (active) setEntities({ entries: Array.isArray(data.entries) ? data.entries : [], invoices: Array.isArray(data.invoices) ? data.invoices : [] }); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [businessId, revision]);
  useEffect(() => { let active = true; setLoading(true); setRows([]); setError(""); Promise.all([workflowRequest<WorkflowOverview>(workflowPath(businessId, "overview")), ["reviews", "evidence", "history", "recurring"].includes(tab) ? workflowRequest<WorkflowRecord[]>(workflowPath(businessId, tab)) : Promise.resolve([])]).then(([data, list]) => { if (active) { setOverview(data); setRows(list); } }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [businessId, tab, revision]);
  async function act(action: () => Promise<unknown>, success = "保存しました", refresh = true) { setBusy(true); setError(""); setMessage(""); try { const result = await action(); setMessage(result && typeof result === "object" && "created" in result ? `作成 ${String((result as { created: number }).created)} 件 / スキップ ${String((result as unknown as { skipped: number }).skipped)} 件 / エラー ${JSON.stringify((result as unknown as { errors: string[] }).errors)}` : success); if (refresh) setRevision(n => n + 1); return result; } catch (e) { setError(e instanceof Error ? e.message : "処理に失敗しました"); } finally { setBusy(false); } }
  const post = (action: string, body: unknown, method = "POST") => workflowRequest(workflowPath(businessId, action), { method, body: JSON.stringify(body) });
  const form = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); return new FormData(event.currentTarget); };
  return <div className="mx-auto max-w-5xl space-y-5"><div><h1 className="text-2xl font-bold">実務管理</h1><p className="mt-2 text-sm text-gray-600">確認・原本保管・月次締めをまとめて管理します。</p></div>
    <nav aria-label="実務管理メニュー" className="flex flex-wrap gap-2">{tabs.map(([id, label]) => <button key={id} type="button" aria-pressed={tab === id} onClick={() => { setTab(id); setMessage(""); }} className={`${button} ${tab === id ? "bg-brand-700 text-white" : "bg-white"}`}>{label}</button>)}</nav>
    {error && <div role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}<button className="ml-3 underline" onClick={() => setRevision(n => n + 1)}>再読み込み</button></div>}{message && <p role="status" className="rounded-lg bg-brand-50 p-3 text-sm text-brand-800">{message}</p>}
    <section className="min-w-0 rounded-xl border bg-white p-4 sm:p-6">{loading ? <p role="status">読み込み中…</p> : <>
      {tab === "overview" && <><h2 className="font-semibold">確認待ち</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{Object.entries(overview?.counts || {}).map(([key, count]) => <div className="rounded-lg bg-brand-50 p-3" key={key}><p className="break-words text-sm">{({ unpaidInvoices: "未入金", overdueInvoices: "期限超過", draftEntries: "仕訳下書き", missingEvidence: "証憑未添付", pendingReviews: "レビュー未対応", unmatchedRows: "未処理明細" } as Record<string, string>)[key] || key}</p><p className="mt-2 text-xl font-semibold">{count} 件</p></div>)}</div><div className="mt-5 flex flex-wrap gap-4 text-sm text-brand-700"><Link to="/invoices">請求・入金を確認 →</Link><Link to="/journal-entries">仕訳を確認 →</Link></div></>}
      {tab === "reviews" && <><h2 className="font-semibold">コメント・修正依頼</h2><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={e => { const f = form(e); void act(() => post("reviews", Object.fromEntries(f))); }}><label className="text-sm">対象<select name="entityType" value={reviewType} onChange={e => { setReviewType(e.target.value); setReviewId(""); }} className={input}><option value="JOURNAL">仕訳</option><option value="INVOICE">請求書</option></select></label><label className="text-sm">対象データ<select name="entityId" required value={reviewId} onChange={e => setReviewId(e.target.value)} className={input}><option value="">対象を選択</option>{options(reviewType)}</select></label><label className="text-sm sm:col-span-2">コメント<textarea name="message" required maxLength={2000} className={input} /></label><label className="text-sm">種類<select name="status" className={input}><option value="COMMENT">コメント</option><option value="CHANGES_REQUESTED">修正依頼</option><option value="APPROVED">確認済み</option></select></label><button disabled={busy} className={button}>投稿</button></form></>}
      {tab === "evidence" && <><h2 className="font-semibold">証憑の原本</h2><p className="mt-2 text-sm text-gray-600">1件256 KiB・事業者5 MiB以内。原本を加工せず保存します。使用量 {Math.round((overview?.evidenceQuota.usedBytes || 0) / 1024)} KiB</p>{!viewer && <form className="mt-4 space-y-3" onSubmit={e => { const f = form(e); for (const key of ["entryId", "invoiceId"]) if (!f.get(key)) f.delete(key); const file = f.get("file"); if (file instanceof File && file.size > 256 * 1024) { setError("原本は256 KiB以下のファイルを選択してください"); return; } void act(() => workflowRequest(workflowPath(businessId, "evidence"), { method: "POST", body: f })); }}><label className="block text-sm">原本ファイル<input type="file" name="file" required className={input} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">仕訳（任意）<select name="entryId" className={input}><option value="">紐付けなし</option>{options("JOURNAL")}</select></label><label className="text-sm">請求書（任意）<select name="invoiceId" className={input}><option value="">紐付けなし</option>{options("INVOICE")}</select></label></div><button className={button} disabled={busy}>原本を保存</button></form>}</>}
      {tab === "history" && <><h2 className="font-semibold">変更履歴</h2><p className="mt-2 text-sm text-gray-500">記録された変更を確認できます。履歴は編集できません。</p></>}
      {tab === "lock" && <><h2 className="font-semibold">締めロック・提出用バックアップ</h2><p className="mt-3 text-sm">最終締日: {overview?.lock?.closedThrough || "未設定"}</p>{owner && <><form className="mt-4 space-y-3" onSubmit={e => { const f = form(e); void act(() => post("lock", { closedThrough: f.get("closedThrough") || null, reason: f.get("reason") })); }}><label className="block text-sm">最終締日（空欄で再開）<input type="date" name="closedThrough" className={input} /></label><label className="block text-sm">理由<input name="reason" required maxLength={500} className={input} /></label><label className="flex gap-2 text-sm"><input type="checkbox" required />指定日までの会計更新が禁止されること、空欄では再開することを確認しました</label><button disabled={busy} className={button}>締め状態を更新</button></form><button className={`${button} mt-5`} disabled={busy} onClick={() => void act(() => downloadWorkflow(workflowPath(businessId, "backup"), `keirio-backup-${businessId}.json`), "提出用JSONをダウンロードしました")}>業務JSONを一括保存</button><p className="mt-2 text-xs text-gray-500">復元検証は隔離したローカル環境で行います。</p></>}</>}
      {tab === "recurring" && <><h2 className="font-semibold">月次の定期下書き</h2><p className="mt-2 text-sm text-gray-500">月1回、最大20件。請求書の送信や仕訳の確定は行いません。</p>{!viewer && <><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={e => { const f = form(e); void act(() => post("recurring", { ...Object.fromEntries(f), dayOfMonth: Number(f.get("dayOfMonth")) })); }}><label className="text-sm">種類<select name="kind" value={recurringKind} onChange={e => { setRecurringKind(e.target.value); setSourceId(""); }} className={input}><option value="JOURNAL">仕訳</option><option value="INVOICE">請求書</option></select></label><label className="text-sm">元データ<select name="sourceId" required value={sourceId} onChange={e => setSourceId(e.target.value)} className={input}><option value="">元データを選択</option>{options(recurringKind)}</select></label><label className="text-sm">名前<input name="name" required maxLength={100} className={input} /></label><label className="text-sm">日（1〜28）<input name="dayOfMonth" type="number" min="1" max="28" defaultValue="1" required className={input} /></label><button disabled={busy} className={button}>定期処理を登録</button></form><form className="mt-5 flex flex-wrap items-end gap-3" onSubmit={e => { const f = form(e); void act(async () => { const result = await post("recurring/run", { month: f.get("month") }) as { created: unknown; skipped: unknown; errors: unknown }; return result; }, "定期処理を実行しました。結果は履歴と下書きを確認してください。"); }}><label className="text-sm">対象月<input type="month" name="month" required className={input} /></label><button disabled={busy} className={button}>下書きを作成</button></form></>}</>}
{tab === "guide" && <><h2 className="font-semibold">入力ガイド</h2><ol className="mt-4 list-inside list-decimal space-y-3 text-sm"><li><Link className="text-brand-700" to="/bank-import">銀行明細を取り込む</Link></li><li><Link className="text-brand-700" to="/journal-entries">仕訳を確認し証憑を添付する</Link></li><li><Link className="text-brand-700" to="/reports/trial-balance">残高を確認して月次締めを行う</Link></li></ol><form className="mt-5 space-y-3" onSubmit={e => { const f = form(e); setGuideMode("suggestions"); void act(async () => setRows(await workflowRequest<WorkflowRecord[]>(workflowPath(businessId, "suggestions", `&query=${encodeURIComponent(text(f.get("query")))}`))), "過去の仕訳を照合しました", false); }}><label className="block text-sm">過去仕訳から候補を探す<input name="query" required maxLength={200} className={input} /></label><button className={button} disabled={busy}>候補を表示</button><p className="text-xs text-gray-500">既存仕訳との照合です。外部AIは使用しません。</p></form><button className={`${button} mt-3`} disabled={busy} onClick={() => { setGuideMode("duplicates"); void act(async () => setRows(await workflowRequest<WorkflowRecord[]>(workflowPath(businessId, "duplicates"))), "重複候補を確認しました", false); }}>重複候補を確認</button>{owner && <form className="mt-6 rounded-lg border p-4" onSubmit={e => { form(e); void act(() => post("sample", { confirm: true }), "サンプルを作成しました"); }}><p className="text-sm">空の事業者だけに学習用サンプルを追加できます。</p><label className="my-3 flex gap-2 text-sm"><input type="checkbox" required />学習用データが追加されることを確認しました</label><button disabled={busy} className={button}>サンプルを追加</button></form>}</>}
      {["reviews", "evidence", "history", "recurring", "guide"].includes(tab) && <div className="mt-5 space-y-3">{rows.length === 0 ? <p className="text-sm text-gray-500">表示するデータはありません。</p> : rows.map((row, index) => <article key={row.id || index} className="min-w-0 rounded-lg border p-3"><dl className="space-y-1 text-sm">{Object.entries(row).filter(([key]) => !["beforeJson", "afterJson", "contentBase64", "before", "after", "lines"].includes(key)).map(([key, value]) => <div key={key} className="flex flex-wrap gap-x-3"><dt className="text-gray-500">{fieldLabels[key] || key}</dt><dd className="min-w-0 break-all">{displayValue(value)}</dd></div>)}</dl>{tab === "history" && <details className="mt-3 text-sm"><summary className="cursor-pointer text-brand-700">変更前・変更後を確認</summary><pre className="mt-2 whitespace-pre-wrap break-all rounded bg-gray-50 p-3 text-xs">{JSON.stringify({ before: row.beforeJson || row.before, after: row.afterJson || row.after }, null, 2)}</pre></details>}<div className="mt-2 flex flex-wrap gap-2">{tab === "evidence" && <button className={button} disabled={busy} onClick={() => void act(() => downloadWorkflow(workflowPath(businessId, `evidence/${encodeURIComponent(row.id)}`), text(row.fileName || row.filename || row.name) || "evidence"), "原本をダウンロードしました")}>原本を取得</button>}{tab === "reviews" && (!viewer || row.userId === user?.id) && row.status !== "RESOLVED" && <button className={button} disabled={busy} onClick={() => void act(() => post(`reviews/${encodeURIComponent(row.id)}`, { status: "RESOLVED" }, "PATCH"))}>対応済みにする</button>}{tab === "recurring" && !viewer && <button className={button} disabled={busy} onClick={() => void act(() => workflowRequest(workflowPath(businessId, `recurring/${encodeURIComponent(row.id)}`), { method: "DELETE" }), "定期処理を解除しました")}>定期処理を解除</button>}</div>{tab === "guide" && guideMode === "suggestions" && !viewer && row.id && <form className="mt-3 space-y-3 border-t pt-3" onSubmit={e => { const f = form(e); void act(() => post(`suggestions/${encodeURIComponent(row.id)}/apply`, { entryDate: f.get("entryDate"), confirm: true }), "候補から下書き仕訳を作成しました"); }}><label className="block text-sm">下書きの取引日<input type="date" name="entryDate" required defaultValue={new Intl.DateTimeFormat("sv-SE", { timeZone: "Asia/Tokyo" }).format(new Date())} className={input} /></label><label className="flex items-start gap-2 text-sm"><input type="checkbox" required className="mt-1" />候補の内容を確認し、下書きを作成します</label><button disabled={busy} className={button}>候補を下書きに追加</button></form>}</article>)}</div>}
    </>}</section></div>;
}
