import { useRef, useState } from "react";
import type { KeyboardEvent, TouchEvent } from "react";
import { ArrowLeft, ArrowRight, BarChart3, BookOpenCheck, Sparkles } from "lucide-react";

const SLIDES = [
  { eyebrow: "DAILY WORK", number: "01", title: "記帳が、迷わず進む。", description: "明細取込から仕訳の確認までを、ひとつの流れに。勘定科目の候補と貸借の整合性が、その場で判断を支えます。", points: ["銀行・カードCSV取込", "仕訳候補をわかりやすく表示", "テンプレートで定型処理を短縮"], visual: "ledger" },
  { eyebrow: "BUSINESS INSIGHT", number: "02", title: "経営の現在地が、見える。", description: "月次損益、現預金の推移、取引先別残高を整理。会計データを、次の判断につながる情報へ変えます。", points: ["損益・貸借・資金繰りを横断", "月次トレンドを視覚化", "予算と実績の差を確認"], visual: "insight" },
  { eyebrow: "CLOSING", number: "03", title: "決算前の焦りを、なくす。", description: "固定資産、減価償却、青色申告決算書まで日々の記帳と接続。期末に必要な作業を順序立てて確認できます。", points: ["決算チェックリスト", "固定資産と減価償却を一元管理", "各種帳票を自動集計"], visual: "closing" },
] as const;

function LedgerVisual() {
  return <div className="product-visual h-full p-4 sm:p-6"><div className="flex items-center justify-between border-b border-[#dce4df] pb-4"><div><p className="text-[10px] font-semibold tracking-[0.18em] text-[#788781]">JOURNAL ENTRY</p><p className="mt-1 font-display text-lg text-[#14231f]">取引を確認</p></div><span className="rounded-full bg-[#e8f1ed] px-3 py-1 text-[11px] font-semibold text-[#216451]">AI候補あり</span></div><div className="mt-5 grid gap-3">{[["10/08", "普通預金", "売上高", "128,000"], ["10/07", "消耗品費", "未払金", "18,420"], ["10/06", "通信費", "普通預金", "7,980"]].map((row, index) => <div key={row[0] + index} className={`grid grid-cols-[3.5rem_1fr_1fr_auto] items-center gap-2 rounded-xl border px-3 py-3 text-xs ${index === 0 ? "border-[#a2c39e] bg-[#f8fbf5] shadow-sm" : "border-[#e1e6e3] bg-white"}`}><span className="text-[#8b9691]">{row[0]}</span><span className="font-medium text-[#283a34]">{row[1]}</span><span className="text-[#65736e]">{row[2]}</span><span className="font-semibold tabular-nums text-[#172720]">¥{row[3]}</span></div>)}</div><div className="mt-4 flex items-center justify-between rounded-xl bg-[#10231e] px-4 py-3 text-white"><span className="flex items-center gap-2 text-xs"><Sparkles size={14} className="text-[#72a881]" />貸借は一致しています</span><span className="text-xs text-[#c7d3ce]">保存準備完了</span></div></div>;
}

function InsightVisual() {
  const bars = [42, 58, 49, 72, 64, 88, 76];
  return <div className="product-visual h-full overflow-hidden bg-[#10231e] p-5 text-white sm:p-7"><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold tracking-[0.18em] text-[#8da39a]">MONTHLY PROFIT</p><p className="mt-2 font-display text-3xl">¥1,284,500</p><p className="mt-1 text-xs text-[#87c7b0]">前月比 +12.4%</p></div><BarChart3 size={22} className="text-[#72a881]" /></div><div className="mt-8 flex h-32 items-end gap-2 sm:gap-3">{bars.map((height, index) => <div key={index} className="flex-1 rounded-t-sm bg-[#2a594b]" style={{ height: `${height}%`, background: index === bars.length - 2 ? "#76a681" : undefined }} />)}</div><div className="mt-3 flex justify-between text-[9px] text-[#758b82]">{["4月", "5月", "6月", "7月", "8月", "9月", "10月"].map((month) => <span key={month}>{month}</span>)}</div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl border border-white/10 bg-white/5 p-3"><p className="text-[10px] text-[#90a29b]">現預金</p><p className="mt-1 font-semibold">¥4,820,000</p></div><div className="rounded-xl border border-white/10 bg-white/5 p-3"><p className="text-[10px] text-[#90a29b]">粗利率</p><p className="mt-1 font-semibold">68.2%</p></div></div></div>;
}

function ClosingVisual() {
  return <div className="product-visual h-full p-5 sm:p-7"><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold tracking-[0.18em] text-[#788781]">YEAR-END CLOSING</p><p className="mt-1 font-display text-xl text-[#14231f]">決算準備</p></div><span className="text-sm font-semibold text-[#25624f]">4 / 6 完了</span></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-[#e6ebe8]"><div className="h-full w-2/3 rounded-full bg-[#357952]" /></div><div className="mt-6 space-y-3">{[[true, "未処理の取引を確認", "確認済み"], [true, "減価償却を計上", "計上済み"], [true, "残高の整合性を確認", "一致"], [false, "決算書を最終確認", "確認待ち"]].map(([done, label, status]) => <div key={String(label)} className="flex items-center gap-3 rounded-xl border border-[#e1e6e3] bg-white px-3.5 py-3"><span className={`flex h-6 w-6 items-center justify-center rounded-full ${done ? "bg-[#e2efe9] text-[#23604d]" : "border border-[#d7ddd9] text-[#9aa49f]"}`}><BookOpenCheck size={13} /></span><span className="flex-1 text-xs font-medium text-[#30413b]">{label}</span><span className="text-[10px] text-[#87938e]">{status}</span></div>)}</div></div>;
}

export default function FeatureCarousel() {
  const [active, setActive] = useState(0);
  const touchStart = useRef<{ x: number; y: number } | null>(null);
  const go = (index: number) => setActive((index + SLIDES.length) % SLIDES.length);
  const onKeyDown = (event: KeyboardEvent<HTMLDivElement>) => { if (event.key === "ArrowLeft") { event.preventDefault(); go(active - 1); } if (event.key === "ArrowRight") { event.preventDefault(); go(active + 1); } };
  const onTouchStart = (event: TouchEvent<HTMLDivElement>) => { touchStart.current = { x: event.touches[0].clientX, y: event.touches[0].clientY }; };
  const onTouchEnd = (event: TouchEvent<HTMLDivElement>) => { if (touchStart.current == null) return; const distance = event.changedTouches[0].clientX - touchStart.current.x; const vertical = event.changedTouches[0].clientY - touchStart.current.y; if (Math.abs(distance) > 45 && Math.abs(distance) > Math.abs(vertical)) go(active + (distance < 0 ? 1 : -1)); touchStart.current = null; };
  const slide = SLIDES[active];
  return <div className="outline-none" role="region" aria-roledescription="carousel" aria-label="Kaikeiの機能紹介" tabIndex={0} onKeyDown={onKeyDown} onTouchStart={onTouchStart} onTouchEnd={onTouchEnd}>
    <div className="grid overflow-hidden rounded-[1.75rem] border border-[#dee8d9] bg-[#ffffff] shadow-[0_24px_70px_rgba(26,38,33,0.10)] lg:grid-cols-[0.9fr_1.1fr]">
      <div className="flex min-h-[30rem] flex-col justify-between p-7 sm:p-10 lg:p-12" aria-live="polite"><div><div className="flex items-center justify-between"><span className="text-[11px] font-semibold tracking-[0.2em] text-[#517b58]">{slide.eyebrow}</span><span className="font-display text-3xl text-[#bdcfb7]">{slide.number}</span></div><h3 className="mt-12 font-display text-3xl leading-tight text-[#13231f] sm:text-4xl">{slide.title}</h3><p className="mt-5 max-w-lg text-sm leading-7 text-[#63716c] sm:text-base">{slide.description}</p><ul className="mt-8 space-y-3">{slide.points.map((point) => <li key={point} className="flex items-center gap-3 text-sm text-[#33443e]"><span className="h-px w-5 bg-[#7da67b]" />{point}</li>)}</ul></div><div className="mt-10 flex items-center justify-between"><div className="flex gap-2" role="group" aria-label="スライドを選択">{SLIDES.map((item, index) => <button key={item.number} type="button" aria-pressed={index === active} aria-label={`${index + 1}枚目: ${item.title}`} onClick={() => go(index)} className={`h-1.5 rounded-full transition-all ${index === active ? "w-10 bg-[#337d54]" : "w-4 bg-[#dce8d7] hover:bg-[#a7bda3]"}`} />)}</div><div className="flex gap-2"><button type="button" onClick={() => go(active - 1)} className="carousel-arrow" aria-label="前の機能"><ArrowLeft size={17} /></button><button type="button" onClick={() => go(active + 1)} className="carousel-arrow" aria-label="次の機能"><ArrowRight size={17} /></button></div></div></div>
      <div className="min-h-[27rem] bg-[#f3f7ee] p-4 sm:p-7 lg:min-h-[36rem] lg:p-10">{slide.visual === "ledger" && <LedgerVisual />}{slide.visual === "insight" && <InsightVisual />}{slide.visual === "closing" && <ClosingVisual />}</div>
    </div>
  </div>;
}
